package Compiler;

public enum Token {
    SELECT, UPDATE, INSERT, DELETE,
    WHERE, FROM, NOT, IN, AND, OR, SET,
    EQUALS, NOT_EQUALS, LESS, LESS_EQUALS,
    GREATER, GREATER_EQUALS, TIMES, VALUES,
    PLUS, MINUS, DIVIDE, WHITESPACE,
    CLIENTE, ESTADO, CREDITO, DEUDA, NOMBRE,
    ZONA, NUMBER, COMMA, LEFT_PARENTHESIS,
    RIGHT_PARENTHESIS, STRING, INVALID
}